### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by AntiHeld889** [hallos/homebridge-cmdtrigger#1]
I get an error on installation

sudo npm install -g homebridge-cmdtrigger
npm ERR! code E404
npm ERR! 404 Not Found: homebridge-cmdtrigger@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-24T16_17_36_559Z-debug.log

**Comment by Krocko** [comment]
Because this Plugin is not on npm.
Install it with `sudo npm install-g https://github.com/hallos/homebridge-cmdtrigger`

**Comment by AntiHeld889** [comment]
thanks Working!
