### ISSUE TITLE
delay doesn't work any more

### ISSUE THREAD

**Issue by smart153** [hallos/homebridge-cmdtrigger#14]
Hi,

I recognized on my Raspberry 3b+ with Homebridge and CMDtrigger-Plugin, that the "delay" for turning off a switch seems to not working any more. The Switch turns off directly after activating it, no matter what delay is set in the config.json.

Example from Log:

[12/8/2020, 8:37:06 AM] [12minHeat] Setting '12minHeat' true
[12/8/2020, 8:37:06 AM] [12minHeat] Command executed: 'dummy'
[12/8/2020, 8:37:07 AM] [12minHeat] Setting '12minHeat' false

Definition in config.json:

"accessory": "CmdTrigger",
"name": "12minHeat",
"command": "dummy",
"delay": "720000",
"execAfterDelay": false

I'm thinking there was no change on that running system before the effect appeared. There is also no other Error thrown...

Thanx & best regards

**Comment by hallos** [comment]
Hi,

Could you check which version of the plugin you are using?

Best regards

**Comment by hallos** [comment]
Hi again,

Update the plugin to 0.3.4 and try again (It may take some time before npm picks up the new version from the git repository). Seems like I introduced a bug in my last update.
Sorry for the inconvenience!

regards,
hallos

**Comment by smart153** [comment]
Thank You for the quick response. Sorry, my mistake, of course You need the Version and Setup...

Homebridge 1.2.3 on Raspberry 3b+ Node.js v12.18.0. | edit: current Plugin-Version 0.3.3, also in the problem-case above

At the moment I don't get the 0.3.4 - I try again later.

**Comment by smart153** [comment]
Problem solved with new Version 0.3.4 from hallos - within some hours! Great, thanx!
