### ISSUE TITLE
chown: /usr/local: Operation not permitted

### ISSUE THREAD

**Issue by samsonrosen** [hallos/homebridge-cmdtrigger#4]
Hi I'm getting the error:

chown: /usr/local: Operation not permitted

**Comment by hallos** [comment]
Hi,
What command are you trying to execute. This is most likeley about user permissons.

**Comment by hallos** [comment]
Aha, is this happening when you try to install ?

**Comment by hallos** [comment]
I have uploaded the plugin to npm registry now. So try to install with npm -g install homebridge-cmdtrigger instead.

**Comment by bubffm** [comment]
Thanks, works.
