### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by bubffm** [hallos/homebridge-cmdtrigger#5]
Does not install. When will this be officially published? Its been years...

**Comment by hallos** [comment]
Hi. I have published it on the npm registry now. Try to install it with npm -g install homebridge-cmdtrigger instead.

**Comment by bubffm** [comment]
all good. thanks

**Comment by sschuste** [comment]
Thanks for publishing the Plugin to the npm registry. This makes things easier and this unholy chown $USER command disappeared from the instructions page. I love it!

**Comment by Kohle81** [comment]
Thanks for publishing to the npm registry!!!! Works fine!

**Comment by hallos** [comment]
Happy to hear that it works for you!
